config/routes.rb
Rails.application.routes.draw do

  # get 'project', :to => 'projects#index', :as => 'project'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :users do
    member do
      get :delete
    end
  end

  resources :projects do
    member do
      get :delete
    end
  end

  resources :tasks do
    member do
      get :delete
    end
  end

  get 'demo/index'
  # if Rails.env.production?
    get '404', :to => 'application#page_not_found'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/program.rb
class Program < ApplicationRecord

  has_and_belongs_to_many :users

  
end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :user
  has_many :tasks

  scope :list, lambda {|query| where(["user_id = ?", "#{query}"]) }
  scope :sorted, lambda { order("created_at ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :sorted_by_name, lambda { order("name ASC") }

  validates_presence_of :name

end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :project
  has_many :todos
  
  scope :list, lambda {|query| where(["project_id = ?", "#{query}"]) }
  scope :sorted, lambda { order("created_at ASC") }
  scope :newest_first, lambda { order("created_at DESC") }

end

app/models/todo.rb
class Todo < ApplicationRecord

  belongs_to :task

  scope :list, lambda {|query| where(["task_id = ?", "#{query}"]) }
  scope :sorted, lambda { order("created_at ASC") }
  scope :newest_first, lambda { order("created_at DESC") }

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :projects
  has_and_belongs_to_many :programs

  scope :sorted, lambda { order('username ASC, first_name ASC, last_name ASC')}

  def name
    "#{first_name} #{last_name}"
    # Or: first_name + ' ' + last_name
    # Or: [first_name, last_name].join(' ')
  end

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  layout 'public'

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
  before_action :load_sessions, :only => :menu
  before_action :setup_navigation, :only => :menu

  def menu
    # display text & links
  end

  def login
    # login form
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
      flash[:notice] = t(:logged_in)
      redirect_to(admin_path)
    else
      flash.now[:notice] = t(:invalid_log)
      render('login')
    end

  end

  def logout
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = t(:logged_out)
    redirect_to(access_login_path)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = t(:please_log_in)
      redirect_to(access_login_path)
      # redirect_to prevents requested action from running
    end
  end

  def setup_navigation
    current_user = User.find(session[:user_id])
    @programUsers = current_user.programs
  end

  def load_sessions
    @userid = session[:user_id]
    @username = session[:username]
  end

  def attempt_module(name)
    found = nil
    @programUsers.each do |programUser|
      if programUser.name == name
        found = programUser.name.inspect
      end
    end

    if found.nil?
      # logger.debug("*** You dont' have access ***")
      redirect_to('/404')
    end
  end

  # def page_not_found
  #   respond_to do |format|
  #     format.html { render template: 'errors/not_found_error', layout: 'layouts/application', status: 404 }
  #     format.all  { render nothing: true, status: 404 }
  #   end
  # end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout false
  
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  layout 'public'

  before_action :confirm_logged_in
  before_action :load_sessions
  before_action :setup_navigation
  before_action :attempt_projects
  before_action :set_project_variables, :only => [:show, :edit, :update]

  def index
    @projects = Project.list(@userid).sorted_by_name.newest_first.limit(10)
  end

  def show
  end

  def new
    @project = Project.new()
  end

  def create
    # Instantiate a new object using form parameters
    @project = Project.new(project_params)
    @project.user_id = @userid
    # Save the object
    if @project.save
      # If save succeeds, redirect to the index action
      flash[:notice] = t(:project_created, as: @project.name)
      redirect_to(projects_path)
    else
      # If save fails, redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
  end

  def update
    # Update the object
    if @project.update_attributes(project_params)
      # If save succeeds, redirect to the show action
      flash[:notice] = t(:project_updated, as: @project.name)
      redirect_to(projects_path)
    else
      # If save fails, redisplay the form so user can fix problems
      render ('edit')
      # render :edit, :locals => {:id => @project.id}
    end
  end

  def delete
  end

  def destory
  end

  private

  def project_params
    params.require(:project).permit(:name, :note)
  end

  def set_project_variables
    @project = Project.find(params[:id])
    @tasks = Task.list(params[:id])
  end

  def attempt_projects
    attempt_module("Project")
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'public'

  before_action :confirm_logged_in
  before_action :load_sessions
  before_action :setup_navigation
  before_action :attempt_users

  def index
    @users = User.all.sorted
  end

  def new
  end

  def create
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  end

  def delete
  end

  def detroy
  end

  private

  def attempt_users
    attempt_module("User")
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/access/login.html.erb
<% @page_title = t :admin_login %>

<div class="login">
  <h1>LOGIN</h1>
  <%= form_tag(access_attempt_login_path, :method => :post) do %>
  <table>
    <tr>
      <td><%= label_tag(:username) %></td>
      <td><%= text_field_tag(:username, params[:username], autofocus: true) %></td>
    </tr>
    <tr>
      <td><%= label_tag(:password) %></td>
      <td><%= password_field_tag(:password) %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag(t :log_in) %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/access/menu.html.erb
<% @page_title = t 'admin_menu' %>

<!-- <div class="menu"> -->
  <h2><%= t 'admin_menu' %></h2>
  <div class="identity"><%= "#{t 'log_in_as', as: @username}" %></div>
  <ul>
    <li><%= link_to("#{t 'manage_projects'}", projects_path) %></li>
    <li><%= link_to("#{t 'manage_admin_users'}", users_path) %></li>
    <li><%= link_to("#{t 'log_out'}", access_logout_path) %></li>
  </ul>
<!-- </div> -->

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, t('error')) %> <%= t('error_continue') %></h2>
    <p><%= t('problems') %></p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/demo/index.html.erb
<h1>Demo#index</h1>
<p>Find me in app/views/demo/index.html.erb</p>

app/views/layouts/_header.html.erb
<nav>
  <%= image_tag('logo_deepblue.png', :alt => 'LOGO', :id => 'logo') %>
  <ul id="menu">
    <% if @userid != nil %>
      <% @programUsers.each do |programUser| %>
      <li><%= link_to("#{t 'view_all', program: programUser.name}", send("#{programUser.name.downcase}s_path")) %></li>
      <% end %>
      <li><%= link_to("#{t 'log_out'}", access_logout_path) %></li>
    <% else %>
      <li><%= link_to("#{t 'log_in'}", access_login_path) %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><% t 'daily_routine' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t 'daily_routine' %><%= " | #{@page_title}" if @page_title %></title>
    <%= stylesheet_link_tag('application', :media => 'all') %>
  </head>
  <body>

    <div id="header">
      <%= render(:partial => 'layouts/header') %>
    </div>

    <div id="main">
      <% if !flash[:notice].blank? %>
        <div class="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <div id="content">
        <%= yield %>
      </div>
    </div>

    <div id="footer">
      <p>&copy; <%= t 'footer' %></p>
    </div>

  </body>
</html>

app/views/projects/_form.html.erb
<%= error_messages_for(f.object) %>

<table>
  <thead>
    <tr class="list">
      <th><%= t 'project_name' %></th>
      <th><%= t 'project_note' %></th>
      <th width="100"></th>
    </tr>
  </thead>
  <tbody>
    <tr class="list">
      <td><%= f.text_field(:name, autofocus: true) %></td>
      <td><%= f.text_field(:note) %></td>
      <td><%= f.submit(submit, :class => 'btn btn-update custom-width') %></td>
    </tr>
  </tbody>
</table>

app/views/projects/delete.html.erb
<h1>Projects#delete</h1>
<p>Find me in app/views/projects/delete.html.erb</p>

app/views/projects/edit.html.erb
<% @page_title = "#{t 's_projects', as: @project.name}" %>

<h2><%= "#{t 'edit_project', as: @project.name}" %></h2>

<%= form_for(@project) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f, submit: t('update_project')}) %>
<% end %>

<h2><em><%= t 'task_list' %></em></h2>

<div>
  <table>
    <tr class="list">
      <th><%= t 'task_name' %></th>
      <th><%= t 'task_note' %></th>
      <th><%= t 'task_done' %></th>
      <th width="100"></th>
      <th width="100"></th>
    </tr>
    <% @tasks.each do |task| %>
    <tr class="list">
      <td><%= link_to(task.name, task_path(task)) %></td>
      <td><%= task.note %></td>
      <td><%= task.done ? 'Yes' : 'No' %></td>
      <td><%= link_to("#{t 'edit'}", edit_task_path(task), :class => 'btn btn-success custom-width') %></td>
      <td><%= link_to("#{t 'delete'}", delete_task_path(task), :class => 'btn btn-danger custom-width') %></td>
    </tr>
    <% end %>
  </table>

</div>
<%= link_to("#{t 'add'} #{t 'new'} #{t 'task'}", new_task_path) %>
<br><br>
<%= link_to("#{t 'back_to_projects'}", projects_path, :class => 'back-link') %>

app/views/projects/index.html.erb
<% @page_title = t 'all_projects' %>

<h2><%= "#{t 's_projects', as: @username}" %></h2>

<div>
  <table>
    <tr class="list">
      <th><%= t 'project_name' %></th>
      <th><%= t 'project_note' %></th>
      <th width="100"></th>
      <th width="100"></th>
    </tr>
    <% @projects.each do |project| %>
    <tr class="list">
      <!-- <%= link_to(project.name, project_path(project, :name => project.name)) %> -->
      <td><%= link_to(project.name, project_path(project)) %></td>
      <td><%= project.note %></td>
      <td><%= link_to("#{t 'edit'}", edit_project_path(project), :class => 'btn btn-success custom-width') %></td>
      <td><%= link_to("#{t 'delete'}", delete_project_path(project), :class => 'btn btn-danger custom-width') %></td>
    </tr>
    <% end %>
  </table>

</div>

<%= link_to("#{t 'add'} #{t 'new'} #{t 'project'}", new_project_path()) %>
<br><br>
<%= link_to("#{t 'back_to_menu'}", admin_path, :class => 'back-link') %>

app/views/projects/new.html.erb
<% @page_title = "#{t 'new_project'}" %>

<h2><%= "#{t 'add_project'}" %></h2>

<%= form_for(@project) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f, submit: t('create_project')}) %>
<% end %>

<%= link_to("#{t 'back_to_projects'}", projects_path, :class => 'back-link') %>

app/views/projects/show.html.erb
<% @page_title = "#{t 's_projects', as: @project.name}" %>

<h2><%= "#{t 's_projects', as: @project.name}" %></h2>
<h2><em><%= t 'task_list' %></em></h2>

<div>
  <table>
    <tr class="list">
      <th><%= t 'task_name' %></th>
      <th><%= t 'task_note' %></th>
      <th><%= t 'task_done' %></th>
      <th width="100"></th>
      <th width="100"></th>
    </tr>
    <% @tasks.each do |task| %>
    <tr class="list">
      <td><%= link_to(task.name, task_path(task)) %></td>
      <td><%= task.note %></td>
      <td><%= task.done ? 'Yes' : 'No' %></td>
      <td><%= link_to("#{t 'edit'}", edit_task_path(task), :class => 'btn btn-success custom-width') %></td>
      <td><%= link_to("#{t 'delete'}", delete_task_path(task), :class => 'btn btn-danger custom-width') %></td>
    </tr>
    <% end %>
  </table>

</div>
<%= link_to("#{t 'add'} #{t 'new'} #{t 'task'}", new_task_path) %>
<br><br>
<%= link_to("#{t 'back_to_projects'}", projects_path, :class => 'back-link') %>

app/views/tasks/delete.html.erb
<h1>Tasks#delete</h1>
<p>Find me in app/views/tasks/delete.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>

<table>
  <thead>
    <tr class="list">
      <th><%= t 'user_name' %></th>
      <th><%= t 'user_pass' %></th>
      <th><%= t 'first_name' %></th>
      <th><%= t 'last_name' %></th>
      <th width="100"></th>
    </tr>
  </thead>
  <tbody>
    <tr class="list">
      <td><%= f.text_field(:username) %></td>
      <td><%= f.password_field(:password) %></td>
      <td><%= f.text_field(:first_name) %></td>
      <td><%= f.text_field(:last_name) %></td>
      <td><%= f.submit(submit, :class => 'btn btn-update custom-width') %></td>
    </tr>
  </tbody>
</table>

app/views/users/delete.html.erb
<h1>User#delete</h1>
<p>Find me in app/views/user/delete.html.erb</p>

app/views/users/edit.html.erb
<% @page_title = "#{t 'edit_user', as: @user.name}" %>

<h2><%= "#{t 'edit_user', as: @user.name}" %></h2>

<%= form_for(@user) do |f| %>
  <%= render(:partial => 'form', :locals => {:f => f, submit: t('update_user')}) %>
<% end %>

<%= link_to("#{t 'view'} #{t 'modules'}", "#") %>
<br><br>
<%= link_to("#{t 'back_to_users'}", users_path, :class => 'back-link') %>

app/views/users/index.html.erb
<% @page_title = t 'list_of_users' %>

<h2><%= "#{t 'list_of_users'}" %></h2>

<div>
  <table>
    <tr class="list">
      <th><%= t 'user_name' %></th>
      <th><%= t 'first_name' %></th>
      <th><%= t 'last_name' %></th>
      <th width="100"></th>
      <th width="100"></th>
    </tr>
    <% @users.each do |user| %>
    <tr class="list">
      <td><%= user.username %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= link_to("#{t 'edit'}", edit_user_path(user), :class => 'btn btn-success custom-width') %></td>
      <td><%= link_to("#{t 'delete'}", delete_user_path(user), :class => 'btn btn-danger custom-width') %></td>
    </tr>
    <% end %>
  </table>

</div>

<%= link_to("#{t 'add'} #{t 'new'} #{t 'users'}", new_user_path()) %>
<br><br>
<%= link_to("#{t 'back_to_menu'}", admin_path, :class => 'back-link') %>

app/views/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>